### ISSUE TITLE
*keyword searches not working in 1.0.2

### ISSUE THREAD

**Issue by gmaciocci** [codeforscience/sciencefair#92]
*keyword searches for searching local collections appear broken on 1.0.2 (mac)

**Comment by blahah** [comment]
does it work if you put a space after the `*`? we currently split it by space, but should just detect a leading `*` instead...

**Comment by gmaciocci** [comment]
It does not

**Comment by blahah** [comment]
@gmaciocci I believe this bug was happening as a result of failed deletion causing errors in the collection. Deletion has been overhauled to eliminate errors in #91, so I think the issue should be resolved in the next release which will auto-update. Closing for now, but please let me know if it occurs again after update.
